definitions:
  dto.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Email va parol bilan kirish, token qaytaradi
      parameters:
      - description: Email va parol
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Foydalanuvchi kirishi (Sign In)
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Yangi foydalanuvchini bazaga qo'shadi va token qaytaradi
      parameters:
      - description: Foydalanuvchi ma'lumotlari
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Foydalanuvchi yaratish (Sign Up)
      tags:
      - Auth
swagger: "2.0"
